### PR TITLE
OpenAPI V3

### PR DESCRIPTION
**Pull request by logan12358**
After these commits:
- The specs are in `/SpeckleSpecs.yaml`, `/paths/*`, and `/schemas/*`. This separation means
   - Commits can be more granular, navigation is easier.
   - Some OpenAPI editors may not work as well. For read-only, you can use `swagger-cli bundle` to resolve external references.
- The build no longer involves `shins` as a submodule.
- Everything is built to a single `html` file.

I don't know if V3 fits in with the roadmap, but it offers some useful things in terms of encoding the API. No obligation to accept this PR, and I'm open to resolving everything back into a single file if using online OpenAPI editors is important.

### CODE REVIEW

**Comment by didimitrie** [comment]
Hey, V3 was defs on the (nonexistent) roadmap! thanks a lot for this PR, looks really good - it's a proper cleanup and scaffolding.

I'll merge! FYI that paw file might make its way back in (was using it for testing via [this](https://paw.cloud/) osx only software as I got frustrated by postman limitations, which might not be valid now + need to check insomnia).

**Comment by logan12358** [comment]
Great! Does the paw file have manually edited parts? Or is it just deterministically generated from the specs? If it's deterministic, we might be able to run it on Travis, which I think has macOS workers.

Just a heads up, I'm working on editing a bunch of the descriptions and fleshing out some of the schemas at the moment. Next steps:
- Check for parity with SpeckleServer (I think comments and some other things might not be quite right)
- Generating API calls in SpeckleCore (and any other client libs) directly from the Specs, and only writing custom code to wrap that

**Comment by didimitrie** [comment]
Wow, you’re on a mission! Great stuff! For sure there are discrepancies with the server, and the core itself (there were some properties that were added or removed in models, same for some responses, etc.)

For generating the .net clients i was using [nswag](https://github.com/RSuter/NSwag <https://github.com/RSuter/NSwag>), but again  it’s a choice that can be revisted - it’s really verbose what comes out.

Forget about the paw file, it’s not important.

**Comment by logan12358** [comment]
A long-term mission, probably!

**Comment by didimitrie** [comment]
From next week onwards i’ll have some more time, so i could put my weight behind this as it’s something i feel it’s needed too. If i don’t get sucked into specklerevit :/

**Pull request merged**
